# Generated by Django 3.1.3 on 2023-10-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
